import Head from 'next/head'
import Image from 'next/image'
import desktop from '../src/assets/index.png';
import mobile from '../src/assets/index-mobile.png';
import {useMobileDetect} from "utils/hooks/useMobileDetect";

export default function Home() {
  const {isMobile} = useMobileDetect();
  const url = isMobile() ? mobile : desktop;
  return (<>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Image src={url} alt="" onClick={() => window.location.href = '/profile'} />
  </>);
}
